stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - pip install pytest pytest-mock requests flask
    - docker-compose up -d
    - sleep 20
    - pytest tests/test_services/test_service1.py -v
    - pytest tests/test_services/test_service2.py -v
    - docker-compose down
  needs:
    - build

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  needs:
    - test