stages:
  - lint
  - build
  - test
  - deploy
 
# defining variables for deployment
variables:
  SSH_USER: "ubuntu"
  SSH_HOST: "195.148.22.168"
  SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"

# 1️⃣ Linting with pylint
lint:
  stage: lint
  image: node:22
  script:
    # Python Linting
    - pip install pylint
    # - pylint **/*.py --fail-under=7
    - pylint --fail-under=7 service1/*.py

    # JavaScript Linting
    - npm install eslint --save-dev
    - npx eslint service2/service2.js

# 2️⃣ Building Docker Image
build:
  stage: build
  script:
    - docker-compose build

# 3️⃣ Running Tests
test:
  stage: test
  script:
    - pip install pytest pytest-mock requests flask
    - docker-compose up -d
    - sleep 10
    - pytest tests/test_services/test_service1.py -v
    - pytest tests/test_services/test_service2.py -v
    - pytest tests/api_gateway/test_api_state.py -v
    - docker-compose down
  needs:
    - build

# 4️⃣ Deploying to CSC VM via SSH
deploy:
  stage: deploy
  before_script:
    - pwd  # Print working directory
    - ls -la  # List all files in current directory
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    # Copy files
    - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no docker-compose.yml $SSH_USER@$SSH_HOST:~/
    - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r nginx service1 service2 $SSH_USER@$SSH_HOST:~/
    
    # Deploy
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        docker-compose down;
        docker-compose up -d --build"
  needs:
    - test