services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    networks:
      - docker-exercise1

  service2:
    build: ./service2
    networks:
      - docker-exercise1
networks:
  docker-exercise1:
    driver: bridge