services:
  nginx:
    build: ./nginx
    ports:
      - "8198:8198" # Web interface
      - "8197:8197" # API
    depends_on:
      - service1-1
      - service1-2
      - service1-3
      - service2
    networks:
      - loadbalancing

  service1-1:
    build: ./service1
    environment:
      - PORT=8199
    networks:
      - loadbalancing

  service1-2:
    build: ./service1
    environment:
      - PORT=8199
    networks:
      - loadbalancing

  service1-3:
    build: ./service1
    environment:
      - PORT=8199
    networks:
      - loadbalancing

  service2:
    build: ./service2
    networks:
      - loadbalancing

networks:
  loadbalancing:
    driver: bridge